// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace NachoClient.iOS
{
	[Register ("NcSimpleColorButton")]
    public partial class NcSimpleColorButton : UIButton
	{

        protected UIColor originalBackgroundColor;
        protected UIColor highlightedColor;

        public NcSimpleColorButton () : base (UIButtonType.Custom)
        {
            Initialize ();
        }

        public NcSimpleColorButton (IntPtr handle) : base (handle)
        {
            Initialize ();
        }

        void Initialize()
        {
            TouchDown += (object sender, EventArgs e) => {
                if (originalBackgroundColor == null){
                    originalBackgroundColor = BackgroundColor;
                    highlightedColor = originalBackgroundColor.ColorWithAlpha(0.5f);
                }
                BackgroundColor = highlightedColor;
            };

            TouchUpInside += (object sender, EventArgs e) => {
                BackgroundColor = originalBackgroundColor;
            };

            TouchDragExit += (object sender, EventArgs e) => {
                BackgroundColor = originalBackgroundColor;
            };

            TouchDragEnter += (object sender, EventArgs e) => {
                if (TouchInside){
                    BackgroundColor = highlightedColor;
                }
            };

            TouchCancel += (object sender, EventArgs e) => {
                BackgroundColor = originalBackgroundColor;
            };
        }
	}
}
