// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using System.Collections.Generic;

using CoreGraphics;
using Foundation;
using UIKit;

using NachoCore;
using NachoCore.Model;
using NachoCore.Utils;

namespace NachoClient.iOS
{
    public partial class AdvancedSettingsViewController : NcUIViewControllerNoLeaks
    {
        McAccount account;
        ILoginFields loginFields;

        UIView greyBackground;

        McCred TestCred;
        List<McServer> SavedList;
        List<McServer> ServerList;

        public delegate void onValidateCallback (McCred creds, List<McServer> servers);

        public AdvancedSettingsViewController () : base ()
        {
        }

        public AdvancedSettingsViewController (IntPtr handle) : base (handle)
        {
        }

        public void Setup (McAccount account)
        {
            this.account = account;
        }

        public override void ViewDidAppear (bool animated)
        {
            base.ViewDidAppear (animated);
            NcApplication.Instance.StatusIndEvent += StatusIndicatorCallback;
        }

        public override void ViewWillDisappear (bool animated)
        {
            base.ViewWillDisappear (animated);
            NcApplication.Instance.StatusIndEvent -= StatusIndicatorCallback;
        }

        protected override void CreateViewHierarchy ()
        {
            NavigationItem.Title = NcServiceHelper.AccountServiceName (account.AccountService);

            var rect = new CGRect (0, 0, View.Frame.Width, View.Frame.Height);
            switch (account.AccountType) {
            case McAccount.AccountTypeEnum.Exchange:
                loginFields = new ExchangeFields (account, null, null, rect, onValidate);
                break;
            case McAccount.AccountTypeEnum.IMAP_SMTP:
                loginFields = new IMapFields (account, null, null, rect, onValidate);
                break;
            default:
                NcAssert.CaseError ();
                break;
            }
            View.AddSubview (loginFields.View);
        }

        protected override void ConfigureAndLayout ()
        {
        }

        protected override void Cleanup ()
        {
        }


        void ShowStatusView ()
        {
            greyBackground = new UIView (NavigationController.View.Frame);
            greyBackground.BackgroundColor = UIColor.DarkGray.ColorWithAlpha (0.4f);
            View.Add (greyBackground);

            UIView statusView = new UIView (new CGRect (View.Frame.Width / 6, View.Frame.Height / 2 - 150, View.Frame.Width * 2 / 3, 150));
            statusView.Layer.CornerRadius = 7.0f;
            statusView.BackgroundColor = UIColor.White;
            statusView.Alpha = 1.0f;

            UITextView statusMessage = new UITextView (new CGRect (8, 2, statusView.Frame.Width - 16, statusView.Frame.Height / 2.4f));
            statusMessage.BackgroundColor = UIColor.White;
            statusMessage.Alpha = 1.0f;
            statusMessage.Font = UIFont.SystemFontOfSize (17);
            statusMessage.TextColor = UIColor.Black;
            statusMessage.Text = NSBundle.MainBundle.LocalizedString ("Validating Credentials", "");
            statusMessage.TextAlignment = UITextAlignment.Center;
            statusMessage.Editable = false;
            statusView.AddSubview (statusMessage);

            UIActivityIndicatorView theSpinner = new UIActivityIndicatorView (UIActivityIndicatorViewStyle.WhiteLarge);
            theSpinner.Alpha = 1.0f;
            theSpinner.HidesWhenStopped = true;
            theSpinner.Frame = new CGRect (statusView.Frame.Width / 2 - 20, 50, 40, 40);
            theSpinner.Color = A.Color_SystemBlue;
            theSpinner.StartAnimating ();

            statusView.AddSubview (theSpinner);

            UIView cancelLine = new UIView (new CGRect (0, 105, statusView.Frame.Width, .5f));
            cancelLine.BackgroundColor = A.Color_NachoLightBorderGray;
            statusView.AddSubview (cancelLine);

            UIButton cancelValidation = new UIButton (new CGRect (0, 106, statusView.Frame.Width, 40));
            cancelValidation.Layer.CornerRadius = 10.0f;
            cancelValidation.BackgroundColor = UIColor.White;
            cancelValidation.TitleLabel.TextAlignment = UITextAlignment.Center;
            cancelValidation.SetTitle (NSBundle.MainBundle.LocalizedString ("Cancel", ""), UIControlState.Normal);
            cancelValidation.AccessibilityLabel = NSBundle.MainBundle.LocalizedString ("Cancel", "");
            cancelValidation.SetTitleColor (A.Color_SystemBlue, UIControlState.Normal);
            statusView.AddSubview (cancelValidation);

            cancelValidation.TouchUpInside += CancelValidationButtonClicked;

            statusView.AddSubview (cancelValidation);

            greyBackground.AddSubview (statusView);
            NavigationController.View.AddSubview (greyBackground);
        }

        void HideStatusView ()
        {
            if (null != greyBackground) {
                greyBackground.RemoveFromSuperview ();
                greyBackground = null;
            }
        }

        void onValidate (McCred cred, List<McServer> servers)
        {
            View.EndEditing (true);

            TestCred = cred;
            SavedList = servers;
            ServerList = new List<McServer> (servers);

            ShowStatusView ();
            StartNextValidation ();
        }

        public override bool HidesBottomBarWhenPushed {
            get {
                return this.NavigationController.TopViewController == this;
            }
        }

        protected override void OnKeyboardChanged ()
        {
            if (null != loginFields) {
                loginFields.Layout (View.Frame.Height - keyboardHeight);
            }
        }

        bool StartNextValidation ()
        {
            var server = ServerList.FirstOrDefault ();
            if (null == server) {
                return false;
            }
            ServerList.RemoveAt (0);

            if (!BackEnd.Instance.ValidateConfig (account.Id, server, TestCred).isOK ()) {
                HandleAccountIssue (NSBundle.MainBundle.LocalizedString ("Network Error", ""), NSBundle.MainBundle.LocalizedString ("A network issue is preventing your changes from being validated. Would you like to save your changes anyway?", ""));
                return false;
            }

            return true;
        }

        void CancelButton_Clicked (object sender, EventArgs e)
        {
            View.EndEditing (true);
            NavigationController.PopViewController (true);
        }

        void StatusIndicatorCallback (object sender, EventArgs e)
        {
            var s = (StatusIndEventArgs)e;

            if ((null == s.Account) || (s.Account.Id != account.Id)) {
                return;
            }

            if (NcResult.SubKindEnum.Info_ValidateConfigSucceeded == s.Status.SubKind) {
                if (!StartNextValidation ()) {
                    SavePasswordAndExit ();
                }
            }
            if (NcResult.SubKindEnum.Error_ValidateConfigFailedComm == s.Status.SubKind) {
                HandleAccountIssue (NSBundle.MainBundle.LocalizedString ("Validation Failed", ""), NSBundle.MainBundle.LocalizedString ("This account may not be able to send or receive emails. Save anyway?", ""));
            }
            if (NcResult.SubKindEnum.Error_ValidateConfigFailedAuth == s.Status.SubKind) {
                HandleAccountIssue (NSBundle.MainBundle.LocalizedString ("Invalid Credentials", ""), NSBundle.MainBundle.LocalizedString ("User name or password is incorrect. No emails can be sent or received. Save anyway?", ""));
            }
            if (NcResult.SubKindEnum.Error_ValidateConfigFailedUser == s.Status.SubKind) {
                HandleAccountIssue (NSBundle.MainBundle.LocalizedString ("Invalid Username", ""), NSBundle.MainBundle.LocalizedString ("User name is incorrect. No emails can be sent or received. Save anyway?", ""));
            }
        }

        void HandleAccountIssue (string title, string message)
        {
            HideStatusView ();
            NcAlertView.Show (this, title, message,
                new NcAlertAction (NSBundle.MainBundle.LocalizedString ("Save", ""), () => {
                    SavePasswordAndExit ();
                }),
                new NcAlertAction (NSBundle.MainBundle.LocalizedString ("Cancel", ""), NcAlertActionStyle.Cancel, null));
        }

        void SavePasswordAndExit ()
        {
            loginFields.Validated (TestCred, SavedList);

            BackEnd.Instance.CredResp (account.Id);

            foreach (var server in SavedList) {
                BackEnd.Instance.ServerConfResp (account.Id, server.Capabilities, false);
            }

            HideStatusView ();
            View.EndEditing (true);
            NavigationController.PopViewController (true);
        }

        protected void CancelValidationButtonClicked (object sender, EventArgs e)
        {
            HideStatusView ();
            BackEnd.Instance.CancelValidateConfig (account.Id);

            NcAlertView.Show (this, NSBundle.MainBundle.LocalizedString ("Validation Cancelled", ""),
                NSBundle.MainBundle.LocalizedString ("Your settings have not been validated. Would you like to save them anyway?", ""),
                new NcAlertAction (NSBundle.MainBundle.LocalizedString ("Save", ""), () => {
                    SavePasswordAndExit ();
                }),
                new NcAlertAction (NSBundle.MainBundle.LocalizedString ("Cancel", ""), NcAlertActionStyle.Cancel, null));
        }
    }
}
