// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using System.IO;
using System.Linq;
using CoreGraphics;
using System.Collections.Generic;

using NachoCore.Utils;

namespace NachoClient.iOS
{
    public partial class AlertChooserViewController : NcUIViewControllerNoLeaks
    {
        UITableView tableView;
        AlertChoicesSource source;

        uint reminder;
        bool reminderIsSet;

        public AlertChooserViewController () : base ()
        {
        }

        public AlertChooserViewController (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();
        }

        protected override void CreateViewHierarchy ()
        {
            tableView = new UITableView (View.Frame, UITableViewStyle.Grouped);
            source = new AlertChoicesSource (this);
            tableView.Source = source;
            tableView.AccessibilityLabel = "Remainder";

            View.Add (tableView);

            NavigationItem.Title = "Reminder";
            Util.SetBackButton (NavigationController, NavigationItem, A.Color_NachoBlue);
        }

        public override void ViewWillAppear (bool animated)
        {
            base.ViewWillAppear (animated);
        }

        protected override void ConfigureAndLayout ()
        {
        }

        protected override void Cleanup ()
        {
            tableView.Source = null;
            tableView.Dispose ();
            tableView = null;
            source = null;
        }

        public override bool HidesBottomBarWhenPushed {
            get {
                return this.NavigationController.TopViewController == this;
            }
        }

        public void SetReminder (bool reminderIsSet, uint reminder)
        {
            this.reminder = reminder;
            this.reminderIsSet = reminderIsSet;
        }

        public bool GetReminder (out uint reminder)
        {
            if (reminderIsSet) {
                reminder = this.reminder;
                return true;
            }
            reminder = 0;
            return false;
        }

        public void Done ()
        {
            NavigationController.PopViewController (true);
        }

        protected class AlertChoicesSource : UITableViewSource
        {
            AlertChooserViewController owner;

            List<uint> choices = new List<uint> (new uint[] { 0, 0, 1, 5, 15, 30, 60, 1440, 2880, 10080 });

            public AlertChoicesSource (AlertChooserViewController owner)
            {
                this.owner = owner;
                // Add the reminder if it's not in our list
                if (!choices.Contains (owner.reminder)) {
                    choices.Add (owner.reminder);
                    choices.Sort ();
                }
            }

            public int IndexOfSelection ()
            {
                NcAssert.NotNull (owner);

                if (!owner.reminderIsSet) {
                    return 0;
                }
                for (var i = 1; i < choices.Count; i++) {
                    if (owner.reminder == choices [i]) {
                        return i;
                    }
                }
                NcAssert.CaseError ();
                return 0;
            }

            public override nint NumberOfSections (UITableView tableView)
            {
                return 1;
            }

            public override nint RowsInSection (UITableView tableview, nint section)
            {
                return choices.Count;
            }

            public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
            {
                const string cellId = "Choice";

                var cell = tableView.DequeueReusableCell (cellId);
                if (null == cell) {
                    cell = new UITableViewCell (UITableViewCellStyle.Default, cellId);
                    if (indexPath.Row == IndexOfSelection ()) {
                        using (var image = UIImage.FromBundle ("gen-checkbox-checked")) {
                            cell.ImageView.Image = image;
                        }
                    } else {
                        using (var image = UIImage.FromBundle ("gen-checkbox")) {
                            cell.ImageView.Image = image;
                        }
                    }
                    cell.TextLabel.TextColor = A.Color_NachoDarkText;
                    cell.TextLabel.Font = A.Font_AvenirNextMedium14;
                    cell.SelectionStyle = UITableViewCellSelectionStyle.Default;
                }
                cell.TextLabel.Text = Pretty.ReminderString (0 != indexPath.Row, choices [indexPath.Row]);
                return cell;
            }

            public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
            {
                if (null != owner) {
                    owner.SetReminder (0 != indexPath.Row, choices [indexPath.Row]);
                    owner.Done ();
                }
            }
        }
    }
}
