// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace NachoClient.iOS
{
	public partial class FilesHierarchyViewController : UITableViewController
	{
		public FilesHierarchyViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
