// This file has been autogenerated from a class added in the UI designer.

using System;
using NachoCore;
using NachoCore.Model;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MimeKit.Utils;
using MimeKit;
using SWRevealViewControllerBinding;

namespace NachoClient.iOS
{
    public partial class MessageViewController : UITableViewController
    {
        McFolder currentFolder { get; set; }

        public void SetFolder (McFolder ncfolder)
        {
            currentFolder = ncfolder;
        }

        public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
        {
            McEmailMessage thisemailmsg;

            if (segue.Identifier == "readmessagesegue") {
                var rdmsg = (ReadMsgController)segue.DestinationViewController; //our destination

                var source = TableView.Source as MessageTableSource;
                var rowPath = TableView.IndexPathForSelectedRow;
                thisemailmsg = source.getEmailMessage (rowPath);
                rdmsg.SetMessage (thisemailmsg);
            }
        }

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();

            // Navigation
            revealButton.Action = new MonoTouch.ObjCRuntime.Selector ("revealToggle:");
            revealButton.Target = this.RevealViewController ();
            this.View.AddGestureRecognizer (this.RevealViewController ().PanGestureRecognizer);

            TableView.Source = new MessageTableSource (currentFolder);
            TableView.ReloadData ();
        }

        public MessageViewController (IntPtr handle) : base (handle)
        {
        }
    }
}
