// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Collections.Generic;
using SWRevealViewControllerBinding;

namespace NachoClient.iOS
{
    public partial class SidebarViewController : UITableViewController
    {
        ///   cellIDs
        ///      "SidebarToAccounts"
        ///      "SidebarToCalendar"
        ///      "SidebarToContacts"
        ///      "SidebarToFolders"
        ///      "SidebarToSettings"

        static List<Tuple<string, string>> crowbarList = new List<Tuple<string, string>> {
            new Tuple<string, string> ("Folders", "SidebarToFolders"),
            new Tuple<string, string> ("AS Contacts", "SidebarToContacts"),
            new Tuple<string, string> ("Device Contacts", "SidebarToContacts"),
//            new Tuple<string, string> ("Merged Contacts", "SidebarToContacts")
        };

        public SidebarViewController (IntPtr handle) : base (handle)
        {
        }

        public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
        {
            Console.WriteLine ("PrepareForSegue: {0}", segue.Identifier);

            NSIndexPath indexPath = this.TableView.IndexPathForSelectedRow;
            UIViewController destViewController = (UIViewController)segue.DestinationViewController;
            destViewController.Title = crowbarList [indexPath.Row].Item1;

            if (segue.GetType () == typeof(SWRevealViewControllerSegue)) {
                Console.WriteLine ("PrepareForSqueue: SWRevealViewControllerSegue");
                SWRevealViewControllerSegue swSegue = (SWRevealViewControllerSegue)segue;
                swSegue.PerformBlock = PerformBlock;
            }
        }

        public void PerformBlock (SWRevealViewControllerSegue s, UIViewController svc, UIViewController dvc)
        {
            Console.WriteLine ("PrepareForSegue: PerformBlock");
            UINavigationController navController = (UINavigationController)this.RevealViewController ().FrontViewController;
            navController.SetViewControllers (new UIViewController[] { dvc }, true);
            this.RevealViewController ().SetFrontViewPosition (FrontViewPosition.Left, true);
        }

        /// <summary>
        /// Called by the TableView to determine how many sections(groups) there are.
        /// </summary>
        public override int NumberOfSections (UITableView tableView)
        {
            return 1;
        }

        /// <summary>
        /// Called by the TableView to determine how many cells to create for that particular section.
        /// </summary>
        public override int RowsInSection (UITableView tableview, int section)
        {
            return crowbarList.Count;
        }

        /// <summary>
        /// Called by the TableView to get the actual UITableViewCell to render for the particular row
        /// </summary>
        public override UITableViewCell GetCell (UITableView tableView, MonoTouch.Foundation.NSIndexPath indexPath)
        {
            var tuple = crowbarList [indexPath.Row];

            UITableViewCell cell = tableView.DequeueReusableCell (tuple.Item2);

            //---- if there are no cells to reuse, create a new one
            if (cell == null) {
                cell = new UITableViewCell (UITableViewCellStyle.Default, tuple.Item2);
            }

            cell.TextLabel.Text = tuple.Item1;

            return cell;
        }
    }
}
